cmake_minimum_required(VERSION 3.22)
project(aii_tts_thread_profile LANGUAGES CXX)
if(NOT WIN32 OR NOT EXISTS "${POCKET_LIBRARY}")
  message(FATAL_ERROR "Explicit retained Windows resident import library required")
endif()
add_executable(aii_tts_thread_profile thread_profile.cpp)
target_compile_features(aii_tts_thread_profile PRIVATE cxx_std_17)
target_compile_options(aii_tts_thread_profile PRIVATE /O2 /W4 /WX /EHsc /fp:strict)
target_link_libraries(aii_tts_thread_profile PRIVATE "${POCKET_LIBRARY}" psapi)
