"""Generate immutable SpeechBrain 1.1.1 frontend coefficients, not model weights."""
import argparse
import hashlib
import json
from pathlib import Path
import speechbrain
import torch
from speechbrain.lobes.features import Fbank
from speechbrain.processing.features import InputNormalization

p = argparse.ArgumentParser()
p.add_argument('destination', type=Path)
p.add_argument('--reference', type=Path, help='Also generate the synthetic C++ regression fixture')
a = p.parse_args()
assert speechbrain.__version__ == '1.1.1'
torch.set_num_threads(2)
f = Fbank(n_mels=80).eval()
b = f.compute_fbanks
central = b.f_central.repeat(b.all_freqs_mat.shape[1],1).T
band = b.band.repeat(b.all_freqs_mat.shape[1],1).T
matrix = b._create_fbank_matrix(central,band)
coefficients = []
bands = []
for m in range(80):
    indices = torch.nonzero(matrix[:,m], as_tuple=False).flatten()
    assert len(indices) and torch.equal(indices, torch.arange(indices[0],indices[-1]+1))
    bands.append((int(indices[0]),len(coefficients),len(indices)))
    coefficients.extend(matrix[indices,m].tolist())
values = {'window':f.compute_STFT.window, 'mel':torch.tensor(coefficients,dtype=torch.float32)}
lines = ['// Generated by generate_tables.py; do not edit coefficients.',
         '#pragma once', '#include <cstddef>', 'namespace aii::ecapa {',
         'struct MelBand { std::size_t first, offset, count; };',
         'static constexpr MelBand bands[80] = {']
lines += ['  {'+', '.join(map(str,row))+'},' for row in bands]
lines.append('};')
hashes = {}
for name,tensor in values.items():
    arr = tensor.detach().cpu().numpy().astype('<f4').reshape(-1)
    hashes[name] = hashlib.sha256(arr.tobytes()).hexdigest()
    lines.append(f'static constexpr float {name}[{len(arr)}] = {{')
    for i in range(0,len(arr),8):
        lines.append('  '+', '.join(float(v).hex()+'f' for v in arr[i:i+8])+',')
    lines.append('};')
lines.append('}')
with a.destination.open('x') as out: out.write('\n'.join(lines)+'\n')
print(json.dumps(hashes))
if a.reference:
    # Deterministic integer PCM, no recording or personal data.
    pcm = torch.tensor([((2*i) & 255) | (((2*i)//251) << 8) for i in range(401)])
    pcm = torch.where(pcm >= 32768, pcm-65536, pcm)
    normalizer = InputNormalization(norm_type='sentence', std_norm=False).eval()
    with torch.inference_mode():
        expected = normalizer(f((pcm.float()/32768).unsqueeze(0)), torch.ones(1)).flatten()
    lines = ['// Synthetic SpeechBrain 1.1.1 reference; generated by generate_tables.py.',
             '#pragma once', 'static constexpr float reference_features[240] = {']
    assert expected.numel() == 240
    for i in range(0,240,8):
        lines.append('  '+', '.join(float(v).hex()+'f' for v in expected[i:i+8])+',')
    lines.append('};')
    with a.reference.open('x') as out: out.write('\n'.join(lines)+'\n')
